name: first-action
description: Here is first-action code

runs:
  echo "first-action in main branch ..."

inputs:
  Project:
    description: Project Name
    required: true
    default: "default-value-project-name"

