name: first-action
description: Here is first-action code

runs:
  using: "composite"
  steps:
    - id: random-number-generator
      run: echo "::set-output name=random-id::$(echo $RANDOM)"
      shell: bash

inputs:
  Project:
    description: Project Name
    required: true
    default: "default-value-project-name"

